using Test
using LinearAlgebra
using SparseArrays
using Statistics
using Tables
using TOML
using Tilia

include("core/mean_regressor.jl")
include("core/derivatives.jl")
include("solvers/least_squares.jl")
include("solvers/coordinate_descent.jl")
include("solvers/iterative.jl")
include("models/linear_regression.jl")
include("models/logistic_regression.jl")
include("models/sparse_regression.jl")
include("models/sparse_logistic.jl")
include("models/decomposition.jl")
include("models/kmeans.jl")
include("models/gaussian_classifiers.jl")
include("models/multinomial_naive_bayes.jl")
include("models/neighbors.jl")
include("models/gaussian_mixture.jl")
include("models/decision_tree.jl")
include("models/forest.jl")
include("models/hist_gradient_boosting.jl")
include("models/isolation_forest.jl")
include("models/kernel_ridge.jl")
include("models/support_vector.jl")
include("models/mlp.jl")
include("models/rbm.jl")
include("reference/phase_b_reference.jl")
include("reference/initial_scope_reference.jl")
include("reference/preprocessing_reference.jl")
include("reference/multinomial_naive_bayes_reference.jl")
include("reference/classification_curves_reference.jl")
include("metrics/metrics.jl")
include("inspection/permutation_importance.jl")
include("model_selection/split_cv.jl")
include("model_selection/evaluate_tune.jl")
include("data/dataset.jl")
include("data/table_preprocessing.jl")
include("data/feature_transforms.jl")
include("kernels/reductions.jl")
include("kernels/logexp.jl")
include("kernels/distances.jl")
include("kernels/losses_sparse.jl")
include("kernels/performance.jl")
include("kernels/statistics_selection.jl")
include("graph/chain.jl")
include("graph/composition.jl")
include("graph/optimization.jl")
include("persistence/structural_roundtrip.jl")
include("conformance/estimator.jl")
include("conformance/catalog.jl")
include("conformance/model_matrix.jl")
include("conformance/allocation_matrix.jl")
include("documentation/public_api.jl")
